services:
  postgres:
    image: postgres:13
    env_file:
      - ./keys.env
    volumes:
      - ./scripts/arvores.sql:/docker-entrypoint-initdb.d/arvores.sql
    ports:
      - "5432:5432"

  arvore_de_links:
    container_name: arvore_de_links
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./arvore_de_links:/arvore_de_links
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./keys.env
    depends_on:
      - postgres
